### PR TITLE
Update all dependencies to support Ember CLI >= 3.5

### PR DESCRIPTION
**Pull request by hakubo**

### CODE REVIEW

**Comment by hakubo** [comment]
When someone updates ember cli to 3.5 this plugin stops working as it uses broccolli 2.0

**Comment by gpoitch** [comment]
Thanks for the PR.  I honestly don't use this anymore so have no intention of testing this out.  I'll trust it works.  Should I bump a major version or is the broccoli stuff backwards compatible?

**Comment by hakubo** [comment]
I tested it against 3.4 where broccoli 2.0 is not enabled by default

**Comment by hakubo** [comment]
but I think since we're bumping major versions of some dependencies it'll be safer to do a major release.

**Comment by gpoitch** [comment]
Published as 1.0.0

**Pull request merged**
